### ISSUE TITLE
Sorry - fairly unclear why the layering w/SystemJS

### ISSUE THREAD

**Issue by CNSKnight** [stealjs/system-bower#24]
If SteelJS is doing what SystemJS does, why the layering?

**Comment by matthewp** [comment]
Not sure what you mean by "layering".  system-bower is an optional extension. It's not in core because it's not used by everyone. Is that what you're asking?

**Comment by CNSKnight** [comment]
Ok got it - somehow something I read early morning had me understanding Systemjs/WITH/SteelJS rather /OR/
